import "./globals.css";

import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import clsx from "clsx";
import type { Metadata } from "next";

import { Inter, Roboto } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["700"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, roboto.variable)}>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
